# title of website
title: 导航

# description of website
description: ylfei's navigation site

# favicon of website
favicon: "https://github.com/ylfei.png?size=40"

# your website url
url: https://ylfei.github.io/web

# github profile url
github: "https://github.com/ylfei/web"

# footer message
footer: Information © 2021-2024 Website by ylf

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    默认: baidu
    # 可选的搜索引擎
    engines:
      - baidu
      - bing
      - bilibili
      - sougou
      

content:
  categories:
    - name: 常用网站
      sites: 
        - name: 金山文档
          description: 可多人实时协作编辑的在线文档
          url: https://www.kdocs.cn
        - name: 中国大学MOOC（慕课）
          description: 中国大学MOOC（慕课）国家精品课程在线学习平台
          url: https://www.icourse163.org/
        - name: 河南地矿职业学院
          description: 河南地矿职业学院官网
          url: http://www.hagmc.edu.cn/
        - name: 阿里云中学堂
          description: 云中学堂”是阿里云培训中心面向客户提供的集“学-练-测-证”于一体的一站式在线学习与实践平台，依托阿里云产品技术与企业实践，提供云计算、大数据、人工智能等多个领域
          url: https://college.aliyun.com
        - name: 阿虚同学的储物间
          description: 实用导航
          url: https://axutongxue.com/
        - name: IT天空
          description: 以系统封装技术与驱动技术为主的综合性IT站点
          url: https://www.itsk.com/
        - name: 今日热榜
          description: 新闻热搜榜
          url: https://tophub.today/c/news
        - name: 测网速
          description: 网络测速
          url: https://www.speedtest.cn/
        - name: my导航
          description: 网站软件收藏
          url: http://yanglf.ysepan.com/
        - name: blog
          description: 博客
          url: https://ylfei.github.io/
        - name:  蛙蛙工具
          description:  便捷的在线工具网站
          url: https://www.iamwawa.cn/
        
    - name: 电子邮箱
      sites:
        - name: 126邮箱
          description: 网易126免费邮箱--你的专业电子邮局
          url: https://mail.126.com/
        - name: 163邮箱
          description: 网易163免费邮箱--中文邮箱第一品牌
          url: https://mail.163.com/
        - name: 腾讯企业邮箱
          description: 腾讯企业邮箱，唯一可以在微信中收发邮件的企业邮箱
          url: https://exmail.qq.com/login/
        - name: 临时邮箱
          description: 临时邮箱、24小时邮箱
          url: http://24mail.chacuo.net/ 
    - name: 影视资源
      sites: 
        - name: 优酷
          description: 视频服务平台,提供视频播放,视频发布,视频搜索,视频分享
          url: https://www.youku.com/
        - name: 爱奇艺
          description: 在线视频网站，海量正版高清视频在线观看
          url: https://www.iqiyi.com/
        - name: 腾讯视频
          description: 在线视频媒体平台，海量高清视频在线观看
          url: https://v.qq.com/
        - name: 哔哩哔哩
          description: bilibili是国内知名的视频弹幕网站
          url: https://www.bilibili.com
        - name: 央视网
          description: 央视网是中央广播电视总台主办的中央重点新闻网站
          url: https://tv.cctv.com/
        - name: 央视纪实
          description: 汇集了央视大量优秀经典纪录片，集纳国内地方台、BBC、国家地理、NHK等
          url: http://jishi.cctv.com/
    
    - name: 软件工具
      sites:
        - name: MSND
          description: MSDN,我告诉你
          url: https://msdn.itellyou.cn/
        - name: Office Tool Plus
          description: 基于Office部署工具制作，除此之外还集成了各种实用性工具
          url: https://otp.landian.vip/zh-cn/
        - name: 小鱼儿yr系统
          description: 专注于系统封装重装系统下载软件分享教程
          url: https://www.yrxitong.com/
        - name: 果核剥壳
          description: 博客类型的资源分享软件，分享绿色软件软件等
          url: https://www.ghxi.com/
        - name: 腾讯软件中心
          description: 提拱海量免费软件安全下载
          url: https://pc.qq.com/
        - name: 正版中国
          description: 以提供正版软件限时免费信息为途径,引导用户养成使用正版软件的习惯
          url: https://www.getitfree.cn/ 
        - name: 枫音应用
          description: 专注分享免费、绿色实用软件
          url: https://www.fy6b.com/
        - name: 大眼仔
          description: 提供各类PC软件,绿色软件,汉化软件,软件教程
          url: http://www.dayanzai.me/
        - name: Ventoy
          description: 新一代多系统启动U盘解决方案
          url: https://www.ventoy.net/cn/index.html
        - name: 奔跑中的奶酪
          description: 技术分享
          url: https://www.runningcheese.com/
        - name: 优启通
          description: 专业U盘启动制作工具
          url: https://www.upe.net/
        - name: 系统总裁
          description: 系统封装，系统封装工具，封装软件
          url: https://www.sysceo.com/
        - name: DLL-FLES
          description: DLL问题解决方案
          url: https://cn.dll-files.com/
        - name: DLL之家
          description: DLL文件搜索
          url: http://www.dllzj.com/
        - name: Snipaste
          description: Snipaste-截图 + 贴图
          url: https://zh.snipaste.com/
        - name: TrafficMonitor
          description: 流量监控器
          url: https://github.com/zhongyang219/TrafficMonitor/releases
        - name: HEU_Activator
          description: HEU
          url: https://github.com/zbezj/HEU_KMS_Activator
        - name: QuickLook
          description: QuickLook
          url: https://github.com/QL-Win/QuickLook    
    - name: 社区资讯  
      sites:
        - name: IT之家
          description: IT科技门户网站。快速精选IT新闻，实时报道科技周边												
          url: https://www.ithome.com/					
        - name: IT天空
          description: 以系统封装技术与驱动技术为主的综合性IT站点
          url: https://www.itsk.com/
        - name: Gitee
          description: Gitee.com(码云) 是 OSCHINA.NET 推出的代码托管平台,支持 Git 和 SVN,提供免费的私有仓库托管
          url: https://gitee.com/
        - name: GitHub
          description: GitHub brings together the world’s largest community of developers to discover.
          url: https://github.com/
    - name: 在线课程
      sites:
        - name: 中国大学MOOC
          description: 中国大学MOOC(慕课) 是国内优质的中文MOOC学习平台
          url: https://www.icourse163.org/
        - name: 大学资源网
          description: 大学资源网致力于为每个希望提升自己能力的人提供学习平台
          url: http://www.dxzy163.com/
        - name: 北京大学公开课
          description: 北京大学公开课
          url: http://opencourse.pku.edu.cn/course/opencourse2/index.html
        - name: 腾讯课堂
          description: 腾讯推出的专业在线教育平台，聚合大量优质教育机构和名师
          url:  https://ke.qq.com/
        - name: 菜鸟教程
          description: 菜鸟教程提供了编程的基础技术教程
          url: https://www.runoob.com/
        - name: w3school
          description: w3school 在线教程
          url: https://www.w3school.com.cn/
    - name: 网络存储   
      sites:
        - name: 阿里云盘
          description: 阿里云盘是一款速度快、不打扰、够安全、易于分享的网盘
          url: https://www.aliyundrive.com/
        - name: 文叔叔
          description: 传文件，找文叔叔（永不限速）
          url: https://www.wenshushu.cn/
        - name: 123云盘
          description: 一键下载分享文件 超大文件快传 免登录下载
          url: https://www.123pan.com/
        - name: 永硕E盘
          description: 数据存储、交流平台,可以保存您的文件、网址、记事等
          url: http://www.ys168.com/ 
    - name: 网页扩展
      sites: 
        - name: Chrome插件
          description: 使用Chrome插件可以为Chrome浏览器带来一些功能性的扩展
          url: https://huajiakeji.com/
        - name: Crx4Chrome插件下载
          description: 用户可以直接在Chrome商店中下载和安装谷歌浏览器插件
          url: http://www.crx4.com/
        - name: Chrome/谷歌浏览器插件
          description: 分享好用靠谱的，Chrome/谷歌浏览器插件
          url: https://www.chrome666.com/
        - name: 扩展迷
          description: 提供Chrome商店/谷歌应用商店里各类Chrome插件下载
          url: https://www.extfans.com/    
        - name: Greasy Fork
          description: Greasy Fork - 安全、实用的用户脚本大全
          url: https://greasyfork.org/zh-CN/scripts?language=all
        - name: Crx搜搜
          description: 浏览器扩展商店
          url: https://www.crxsoso.com/
        - name: CrxDL
          description: 浏览器扩展离线安装包
          url: https://crxdl.com/
    - name: PDF转换
      sites:
        - name: PDF2GO
          description: 免费的在线PDF转换器
          url:  https://www.pdf2go.com/zh
        - name:  iLovePDF
          description: 免费支持15MB的PDF转换
          url: https://www.ilovepdf.com/zh-cn
        - name: ALL TO ALL
          description: 在线格式转换
          url: https://www.alltoall.net
    - name: 在线配色
      sites:
        - name: SDC优设网配色工具
          description: 优设网帮助您完成配色方案，不用配色软件轻松配色
          url: https://color.uisdc.com/
        - name: HTML拾色器
          description: HTML拾色器
          url: https://www.runoob.com/tags/html-colorpicker.html
        - name: 中国传统颜色
          description: 中国传统颜色
          url: http://zhongguose.com/
    - name: 字体资源
      sites: 
        - name: 站长字体
          description: 字体库提供,中文字体下载,英文字体下载,书法字体下载,方正字体下载等字体免费下载
          url: https://font.chinaz.com/
        - name: 找字网
          description: 提供中英文免费字体下载
          url: http://www.zhaozi.cn/
        - name: 字体之家
          description: 字体之家提供最全的免费手机字体和手机软件下载
          url: http://www.17ziti.com/
        - name: 方正字库
          description: 方正字库官方网站
          url: http://www.foundertype.com/
        - name: 字体传奇网
          description: 中国首个字体品牌设计师交流网
          url: http://ziticq.com/
    - name: 网址导航
      sites:
        - name: 有趣网站之家
          description: 分享有趣的国内外网站，应用新奇的html5网站
          url: https://youquhome.com/
        - name: 阿虚同学的储物间
          description: 实用导航
          url: https://axutongxue.gitee.io/
        - name: 考拉新媒体导航
          description: 考拉新媒体导航，新媒体人的专属门户网站
          url: https://www.kaolamedia.com/
        - name: my导航
          description: ysepan.com
          url: http://yanglf.ysepan.com/
        - name: 新媒体导航
          description: 工具推荐服务，是一个优秀、绿色、安全、好用的新媒体助手
          url: http://123.meibp.com/
        - name: 学术屋
          description: 学术屋导航
          url: http://sci.xueshuwu.cn/
